export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED+PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
